### PR TITLE
Fix http-json plugin by always converting expected value to string

### PR DESCRIPTION
**Pull request by thbkrkr**

### CODE REVIEW

**Comment by NicolasLM** [comment]
Hi Thibault,

Thank you for your contribution. It looks legit, however could you add a simple test case for this?
You can add it there https://github.com/NicolasLM/sauna/blob/master/tests/test_plugins.py#L638

**Comment by thbkrkr** [comment]
Of course! Here is the test.

**Comment by NicolasLM** [comment]
Thanks, do you need a release on PyPI?

**Comment by thbkrkr** [comment]
It's not necessary. I run sauna in Docker by cloning a specific tag/sha1. Thanks.

**Pull request merged**
