### PR TITLE
Allow concurrency in checks

### PR DESCRIPTION
**Pull request by geoffreybauduin**
Features:

- concurrency parameter: if provided and greater than 1, you can run multiple checks concurrently (defaults to 1, default behavior).

This may be a specific use case, but useful for a lot of people. Indeed, when running a huge amount of checks, that sometime can take seconds to process, we sometimes go from 1 check per minute (depend on my configuration) to 1 check every 3 minute (because of some checks taking too much time)

### CODE REVIEW

**Comment by NicolasLM** [comment]
Hey,

Thanks you for your contribution! This feature is nice but it suffers from an issue that is a bit counter intuitive: if you have a slow check the thread pool can be easily filled with N instances of the same check.

I'm not sure how to tackle this problem. Maybe by maintaining a list of checks currently running to avoid submitting twice the same one to the thread pool.

You can reproduce the issue with the following configuration sample: 
```
---
periodicity: 1
concurrency: 10

consumers:

  - type: Stdout

plugins:

  - type: HTTP
    checks:
      - type: request
        url: https://www.google.fr
        verify_ca_crt: true
        method: GET
        code: 200
        content: Google
        timeout: 50000
        warn: 10000
        crit: 50000

  - type: HTTP
    checks:
      - type: request
        name: foo
        url: https://213.22.232.2
        verify_ca_crt: true
        method: GET
        code: 200
        timeout: 50000
        warn: 10000
        crit: 50000
```

**Comment by geoffreybauduin** [comment]
Hey,

I quickly made a list with `check.name`. I also specified in the documentation about this restriction.
It could be up to anybody to modify this behavior and add another strategy.

If you need me to squash the PR or specify anything else, don't hesitate @NicolasLM.

FYI, we made this available on our production infrastructure this afternoon, with concurrency, everything is doing ok.

**Comment by geoffreybauduin** [comment]
@NicolasLM ~~we are currently reviewing an issue on concurrency side, some checks are not done anymore with this patch, i'll let you know~~

**Comment by geoffreybauduin** [comment]
-- Quick update

checks are effectively done, I was upgrading from 0.0.11 to "master" version, and didn't catch the `.lower` there https://github.com/NicolasLM/sauna/blob/master/sauna/__init__.py#L237

Everything looks good on our side

**Comment by NicolasLM** [comment]
Hey,

Sorry for the delay.

It seems that `self._current_checks` can be read and written simultaneously from different thread.

I know that in CPython this is unlikely to ever cause any trouble, but still, better safe than sorry. Could you please add a lock that will protect reads and writes to this variable? The lock can be an attribute of the class like `self._current_checks_lock`.

After that you can squash your commit and I will merge it. Thanks

**Comment by geoffreybauduin** [comment]
You're the boss!

I just reported the modification you asked for, and squashed my commits.

**Comment by NicolasLM** [comment]
Awesome, thank you.

**Pull request merged**
